### ISSUE TITLE
NRE в геймплее

### ISSUE THREAD

**Issue by Red-Cat-Fat** [votizlov/Team-shooter#3]
![image](https://user-images.githubusercontent.com/28541280/81606139-31bfdd80-93db-11ea-84ad-5d4b5350e859.png)
При нажатии на E или Q:
![image](https://user-images.githubusercontent.com/28541280/81606213-52883300-93db-11ea-9d31-29bb0a2a4cd7.png)

**Comment by votizlov** [comment]
О нет, после того, как я добавил мультиплеер, я не переделал инициализацию игрока
