### ISSUE TITLE
Копипасти с умом

### ISSUE THREAD

**Issue by Red-Cat-Fat** [votizlov/Team-shooter#6]
Если что-то копипастишь - разберись как это работает. Я про компонент SimpleCameraController
Кодстайл из левого проекта, описания на английском, управление на WASD, которое в проекте не работает и т.п.

**Comment by Red-Cat-Fat** [comment]
Проверил в сцене. Я так понял, что ты его не используешь. Тогда зачем оставил?

**Comment by votizlov** [comment]
Это создалось из-за того, что при создании проекта я выбрал URP, и там материалы начальные и все настроено, чтоб шейдеры использовать. Там есть сцена для примера, и чтоб ее получше рассмотреть используется этот скрипт управления камерой. Даже не заметил его.

**Comment by Red-Cat-Fat** [comment]
Удаляй то, что не используешь
